create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password text not null,
  phone text,
  address text,
  bio text,
  photo_path text,
  gender text,
  birth_date text,
  created_at text not null
);

alter table public.users drop column if exists role;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  seller_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  price text not null,
  rating double precision default 0.0,
  "reviewCount" integer default 0,
  category text default 'Semua',
  condition text default 'Pernah Dipakai',
  "storeName" text not null,
  location text not null,
  "imageUrl" text not null,
  "isFavorite" integer default 0,
  badge text,
  "isBid" integer default 0,
  end_time text,
  description text
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  sort_order integer default 0,
  created_at text not null default now()::text
);

create table if not exists public.user_favorites (
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at text not null default now()::text,
  primary key (user_id, product_id)
);

create table if not exists public.cart_items (
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  created_at text not null default now()::text,
  primary key (user_id, product_id)
);

create table if not exists public.bids (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  buyer_id bigint not null references public.users(id) on delete cascade,
  amount integer not null,
  created_at text not null
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  buyer_id bigint not null constraint orders_buyer_id_fkey references public.users(id) on delete cascade,
  seller_id bigint not null constraint orders_seller_id_fkey references public.users(id) on delete cascade,
  total_amount integer not null,
  status text default 'Menunggu',
  payment_method text not null,
  shipping_address text,
  shipping_method text default 'EcoExpress',
  shipping_cost integer default 0,
  service_fee integer default 0,
  discount integer default 0,
  created_at text not null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  "iconName" text not null,
  "iconColorHex" text not null,
  "iconBgColorHex" text not null,
  title text not null,
  time text not null,
  description text not null,
  "isUnread" integer default 0
);

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  type text not null,
  name text not null,
  account_number text not null,
  is_default integer default 0,
  image_url text
);

create table if not exists public.help_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  category text not null,
  message text not null,
  created_at text not null
);

create table if not exists public.password_reset_otps (
  id bigint generated by default as identity primary key,
  email text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_rooms (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  buyer_id bigint not null references public.users(id) on delete cascade,
  seller_id bigint not null references public.users(id) on delete cascade,
  last_message text,
  last_message_at text,
  created_at text not null default now()::text,
  unique (product_id, buyer_id, seller_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.chat_rooms(id) on delete cascade,
  sender_id bigint not null references public.users(id) on delete cascade,
  message text not null,
  offer_amount integer,
  is_read integer default 0,
  created_at text not null default now()::text
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  reviewer_id bigint not null references public.users(id) on delete cascade,
  seller_id bigint not null references public.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text,
  created_at text not null default now()::text,
  unique (order_id, reviewer_id)
);

create extension if not exists pg_trgm with schema extensions;

create index if not exists idx_products_id_desc on public.products (id desc);
create index if not exists idx_products_category on public.products (category);
create index if not exists idx_products_is_bid on public.products ("isBid");
create index if not exists idx_products_seller_id on public.products (seller_id);
create index if not exists idx_products_name_trgm on public.products using gin (name gin_trgm_ops);
create index if not exists idx_product_images_product_id on public.product_images (product_id, sort_order);
create index if not exists idx_user_favorites_user_id on public.user_favorites (user_id, created_at desc);
create index if not exists idx_cart_items_user_id on public.cart_items (user_id, created_at desc);
create index if not exists idx_bids_product_amount on public.bids (product_id, amount desc);
create index if not exists idx_orders_buyer_id on public.orders (buyer_id, id desc);
create index if not exists idx_orders_seller_id on public.orders (seller_id, id desc);
create index if not exists idx_chat_rooms_buyer_id on public.chat_rooms (buyer_id, last_message_at desc);
create index if not exists idx_chat_rooms_seller_id on public.chat_rooms (seller_id, last_message_at desc);
create index if not exists idx_chat_messages_room_id on public.chat_messages (room_id, id);
create index if not exists idx_chat_messages_unread on public.chat_messages (room_id, sender_id, is_read);
create index if not exists idx_password_reset_otps_email_created on public.password_reset_otps (email, created_at desc);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.chat_messages;
    alter publication supabase_realtime add table public.notifications;
  end if;
exception
  when duplicate_object then null;
end $$;

alter table public.orders add column if not exists shipping_address text;
alter table public.orders add column if not exists shipping_method text default 'EcoExpress';
alter table public.orders add column if not exists shipping_cost integer default 0;
alter table public.orders add column if not exists service_fee integer default 0;
alter table public.orders add column if not exists discount integer default 0;
alter table public.notifications add column if not exists user_id bigint references public.users(id) on delete cascade;
alter table public.payment_methods add column if not exists user_id bigint references public.users(id) on delete cascade;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', true)
on conflict (id) do update set public = excluded.public;

alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.user_favorites enable row level security;
alter table public.cart_items enable row level security;
alter table public.bids enable row level security;
alter table public.orders enable row level security;
alter table public.notifications enable row level security;
alter table public.payment_methods enable row level security;
alter table public.help_messages enable row level security;
alter table public.password_reset_otps enable row level security;
alter table public.chat_rooms enable row level security;
alter table public.chat_messages enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "allow anon read users" on public.users;
drop policy if exists "allow anon insert users" on public.users;
drop policy if exists "allow anon update users" on public.users;
drop policy if exists "allow anon delete users" on public.users;
drop policy if exists "allow anon all products" on public.products;
drop policy if exists "allow anon all product_images" on public.product_images;
drop policy if exists "allow anon all user_favorites" on public.user_favorites;
drop policy if exists "allow anon all cart_items" on public.cart_items;
drop policy if exists "allow anon all bids" on public.bids;
drop policy if exists "allow anon all orders" on public.orders;
drop policy if exists "allow anon all notifications" on public.notifications;
drop policy if exists "allow anon all payment_methods" on public.payment_methods;
drop policy if exists "allow anon all help_messages" on public.help_messages;
drop policy if exists "deny anon password reset otp access" on public.password_reset_otps;
drop policy if exists "allow anon all chat_rooms" on public.chat_rooms;
drop policy if exists "allow anon all chat_messages" on public.chat_messages;
drop policy if exists "allow anon all reviews" on public.reviews;
drop policy if exists "allow authenticated all users" on public.users;
drop policy if exists "allow authenticated all products" on public.products;
drop policy if exists "allow authenticated all product_images" on public.product_images;
drop policy if exists "allow authenticated all user_favorites" on public.user_favorites;
drop policy if exists "allow authenticated all cart_items" on public.cart_items;
drop policy if exists "allow authenticated all bids" on public.bids;
drop policy if exists "allow authenticated all orders" on public.orders;
drop policy if exists "allow authenticated all notifications" on public.notifications;
drop policy if exists "allow authenticated all payment_methods" on public.payment_methods;
drop policy if exists "allow authenticated all help_messages" on public.help_messages;
drop policy if exists "allow authenticated all chat_rooms" on public.chat_rooms;
drop policy if exists "allow authenticated all chat_messages" on public.chat_messages;
drop policy if exists "allow authenticated all reviews" on public.reviews;
drop policy if exists "allow anon product image reads" on storage.objects;
drop policy if exists "allow anon product image uploads" on storage.objects;
drop policy if exists "allow anon product image updates" on storage.objects;
drop policy if exists "allow anon product image deletes" on storage.objects;
drop policy if exists "allow anon profile photo reads" on storage.objects;
drop policy if exists "allow anon profile photo uploads" on storage.objects;
drop policy if exists "allow anon profile photo updates" on storage.objects;
drop policy if exists "allow anon profile photo deletes" on storage.objects;
drop policy if exists "allow authenticated product image reads" on storage.objects;
drop policy if exists "allow authenticated product image uploads" on storage.objects;
drop policy if exists "allow authenticated product image updates" on storage.objects;
drop policy if exists "allow authenticated product image deletes" on storage.objects;
drop policy if exists "allow authenticated profile photo reads" on storage.objects;
drop policy if exists "allow authenticated profile photo uploads" on storage.objects;
drop policy if exists "allow authenticated profile photo updates" on storage.objects;
drop policy if exists "allow authenticated profile photo deletes" on storage.objects;

create policy "allow anon read users" on public.users
  for select to anon using (true);
create policy "allow anon insert users" on public.users
  for insert to anon with check (true);
create policy "allow anon update users" on public.users
  for update to anon using (true) with check (true);
create policy "allow anon delete users" on public.users
  for delete to anon using (true);

create policy "allow anon all products" on public.products
  for all to anon using (true) with check (true);
create policy "allow anon all product_images" on public.product_images
  for all to anon using (true) with check (true);
create policy "allow anon all user_favorites" on public.user_favorites
  for all to anon using (true) with check (true);
create policy "allow anon all cart_items" on public.cart_items
  for all to anon using (true) with check (true);
create policy "allow anon all bids" on public.bids
  for all to anon using (true) with check (true);
create policy "allow anon all orders" on public.orders
  for all to anon using (true) with check (true);
create policy "allow anon all notifications" on public.notifications
  for all to anon using (true) with check (true);
create policy "allow anon all payment_methods" on public.payment_methods
  for all to anon using (true) with check (true);
create policy "allow anon all help_messages" on public.help_messages
  for all to anon using (true) with check (true);
create policy "deny anon password reset otp access" on public.password_reset_otps
  for all to anon using (false) with check (false);
create policy "allow anon all chat_rooms" on public.chat_rooms
  for all to anon using (true) with check (true);
create policy "allow anon all chat_messages" on public.chat_messages
  for all to anon using (true) with check (true);
create policy "allow anon all reviews" on public.reviews
  for all to anon using (true) with check (true);

create policy "allow authenticated all users" on public.users
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all products" on public.products
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all product_images" on public.product_images
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all user_favorites" on public.user_favorites
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all cart_items" on public.cart_items
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all bids" on public.bids
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all orders" on public.orders
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all notifications" on public.notifications
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all payment_methods" on public.payment_methods
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all help_messages" on public.help_messages
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all chat_rooms" on public.chat_rooms
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all chat_messages" on public.chat_messages
  for all to authenticated using (true) with check (true);
create policy "allow authenticated all reviews" on public.reviews
  for all to authenticated using (true) with check (true);

create policy "allow anon product image reads" on storage.objects
  for select to anon using (bucket_id = 'product-images');
create policy "allow anon product image uploads" on storage.objects
  for insert to anon with check (bucket_id = 'product-images');
create policy "allow anon product image updates" on storage.objects
  for update to anon using (bucket_id = 'product-images') with check (bucket_id = 'product-images');
create policy "allow anon product image deletes" on storage.objects
  for delete to anon using (bucket_id = 'product-images');

create policy "allow anon profile photo reads" on storage.objects
  for select to anon using (bucket_id = 'profile-photos');
create policy "allow anon profile photo uploads" on storage.objects
  for insert to anon with check (bucket_id = 'profile-photos');
create policy "allow anon profile photo updates" on storage.objects
  for update to anon using (bucket_id = 'profile-photos') with check (bucket_id = 'profile-photos');
create policy "allow anon profile photo deletes" on storage.objects
  for delete to anon using (bucket_id = 'profile-photos');

create policy "allow authenticated product image reads" on storage.objects
  for select to authenticated using (bucket_id = 'product-images');
create policy "allow authenticated product image uploads" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images');
create policy "allow authenticated product image updates" on storage.objects
  for update to authenticated using (bucket_id = 'product-images') with check (bucket_id = 'product-images');
create policy "allow authenticated product image deletes" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images');

create policy "allow authenticated profile photo reads" on storage.objects
  for select to authenticated using (bucket_id = 'profile-photos');
create policy "allow authenticated profile photo uploads" on storage.objects
  for insert to authenticated with check (bucket_id = 'profile-photos');
create policy "allow authenticated profile photo updates" on storage.objects
  for update to authenticated using (bucket_id = 'profile-photos') with check (bucket_id = 'profile-photos');
create policy "allow authenticated profile photo deletes" on storage.objects
  for delete to authenticated using (bucket_id = 'profile-photos');

insert into public.users (id, name, email, password, phone, address, created_at)
values
  (1, 'Keandra', 'seller1@thrift.in', 'password123', '081234567890', 'Jl. Malang Raya No 1', now()::text),
  (2, 'Andhika', 'buyer1@thrift.in', 'password123', '081298765432', 'Jl. Surakarta No 5', now()::text)
on conflict (id) do nothing;

insert into public.products (
  id,
  seller_id,
  "imageUrl",
  rating,
  "reviewCount",
  name,
  category,
  condition,
  "storeName",
  location,
  price,
  "isFavorite",
  badge,
  "isBid",
  description
)
values
  (1, 1, 'https://picsum.photos/seed/cozyknit/300/300', 4.9, 127, 'Cozy Knit Cardigan Vintage', 'Pakaian', 'Pernah Dipakai', 'Keandra''s Attic', 'Malang', '225000', 0, 'Sangat Bagus', 0, 'Cardigan vintage nyaman untuk harian.'),
  (2, 1, 'https://picsum.photos/seed/silverjewel/300/300', 4.8, 89, 'Minimalist Silver Bracelet Set', 'Aksesoris', 'Baru', 'Kenzie''s Attic', 'Tangerang', '450000', 0, 'Langka', 0, 'Set gelang silver minimalis.')
on conflict (id) do nothing;

insert into public.product_images (product_id, image_url, sort_order)
select p.id, p."imageUrl", 0
from public.products p
where not exists (
  select 1 from public.product_images pi where pi.product_id = p.id
);

update public.notifications set user_id = 2 where user_id is null;
update public.payment_methods set user_id = 2 where user_id is null;

insert into public.reviews (product_id, reviewer_id, seller_id, rating, comment, created_at)
values
  (1, 2, 1, 5, 'Barang sesuai foto dan seller responsif.', now()::text),
  (2, 2, 1, 5, 'Kondisi bagus, pengiriman cepat.', now()::text)
on conflict do nothing;

delete from public.products
where seller_id = 1
  and "isBid" = 1
  and name in (
    'Levi''s 750S Trucker Jacket',
    'Vintage Y3 Originals Multi-Color Jacket',
    'Heritage Leather Brown Bag'
  );

select setval(pg_get_serial_sequence('public.users', 'id'), coalesce(max(id), 1), true) from public.users;
select setval(pg_get_serial_sequence('public.products', 'id'), coalesce(max(id), 1), true) from public.products;
select setval(pg_get_serial_sequence('public.product_images', 'id'), coalesce(max(id), 1), true) from public.product_images;
select setval(pg_get_serial_sequence('public.reviews', 'id'), coalesce(max(id), 1), true) from public.reviews;
