create table if not exists public.password_reset_otps (
  id bigint generated by default as identity primary key,
  email text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_password_reset_otps_email_created
  on public.password_reset_otps (email, created_at desc);

alter table public.password_reset_otps enable row level security;

drop policy if exists "deny anon password reset otp access" on public.password_reset_otps;

create policy "deny anon password reset otp access" on public.password_reset_otps
  for all to anon using (false) with check (false);
