create table if not exists public.user_fcm_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token text unique not null,
  platform text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_fcm_tokens_user_id
  on public.user_fcm_tokens (user_id);

alter table public.user_fcm_tokens enable row level security;

drop policy if exists "allow anon all user_fcm_tokens"
  on public.user_fcm_tokens;
drop policy if exists "allow authenticated all user_fcm_tokens"
  on public.user_fcm_tokens;

create policy "allow anon all user_fcm_tokens"
  on public.user_fcm_tokens
  for all to anon using (true) with check (true);

create policy "allow authenticated all user_fcm_tokens"
  on public.user_fcm_tokens
  for all to authenticated using (true) with check (true);
